---
- debug: msg='Running tasks for jail {{ jail_hostname }}'

- name: Check if jail already exists
  shell: /usr/local/sbin/iocage get host_hostuuid {{ jail_hostname }}
  ignore_errors: true
  changed_when: false
  register: jail_exists

- name: Get running FreeBSD version
  shell: uname -r | sed -E 's,-p[0-9]+,,'
  register: jail_host_release_version
  changed_when: false

- name: Create jail
  command: /usr/local/sbin/iocage create -n {{ jail_hostname }} ip4_addr={{ jail_net_ip }} -r {{ jail_release_version | default(jail_host_release_version.stdout) }}
  when: jail_exists|failed
  register: jail_created
  notify:
  - Start iocage

- name: Get jail s UUID
  shell: /usr/local/sbin/iocage get host_hostuuid {{ jail_hostname }}
  changed_when: false
  register: jail_uuid

- name: Set jail properties
  command: /usr/local/sbin/iocage set {{ item }} {{ jail_uuid.stdout }}
  with_items:
  - 'boot=on'
  - 'host_hostname={{ jail_hostname }}'
  when: jail_created|changed

- name: Register home diretory
  command: echo {{ host_ioc_jails_dir }}/{{ jail_uuid.stdout }}/root
  changed_when: false
  register: jail_home

